name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag my-image-name:$(date +%s) .

      - name: Run the Docker container
        run: docker run -p 5000:5000 my-image-name:$(date +%s)
